Revert "quote startup options"
This reverts commit 612d0b02a835309602731822642bbe8aba245063.

The reverted commit led to

```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Unrecognized VM option 'UseContainerSupport -XX:InitialRAMPercentage=25 -XX:MaxRAMPercentage=65'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```